import { SetMetadata } from '@nestjs/common';

export const PERMISSIONS_KEY = 'permissions';

/**
 * @Permissions() decorator - requires user to have specific permissions
 * 
 * Usage:
 * @Permissions('PEOPLE_ARCHIVE_WRITE')
 * @Post('archives')
 * createArchive() { ... }
 */
export const Permissions = (...permissions: string[]) =>
    SetMetadata(PERMISSIONS_KEY, permissions);

// Permission constants matching SPEC/05_RBAC.md
export const Permission = {
    // 人员管理
    PEOPLE_ARCHIVE_READ: 'PEOPLE_ARCHIVE_READ',
    PEOPLE_ARCHIVE_WRITE: 'PEOPLE_ARCHIVE_WRITE',
    PEOPLE_ARCHIVE_IMPORT: 'PEOPLE_ARCHIVE_IMPORT',
    PEOPLE_ARCHIVE_EXPORT: 'PEOPLE_ARCHIVE_EXPORT',
    PEOPLE_PRE_RECORD_READ: 'PEOPLE_PRE_RECORD_READ',
    PEOPLE_PRE_RECORD_WRITE: 'PEOPLE_PRE_RECORD_WRITE',
    PEOPLE_APPROVAL_READ: 'PEOPLE_APPROVAL_READ',
    PEOPLE_APPROVAL_WRITE: 'PEOPLE_APPROVAL_WRITE',
    PEOPLE_BLACKLIST_READ: 'PEOPLE_BLACKLIST_READ',
    PEOPLE_BLACKLIST_WRITE: 'PEOPLE_BLACKLIST_WRITE',
    PEOPLE_ORG_READ: 'PEOPLE_ORG_READ',
    PEOPLE_ORG_WRITE: 'PEOPLE_ORG_WRITE',

    // 消费管理
    CONSUME_ACCOUNT_READ: 'CONSUME_ACCOUNT_READ',
    CONSUME_ACCOUNT_WRITE: 'CONSUME_ACCOUNT_WRITE',
    CONSUME_TRADE_READ: 'CONSUME_TRADE_READ',
    CONSUME_TRADE_CORRECT: 'CONSUME_TRADE_CORRECT',
    CONSUME_REFUND_READ: 'CONSUME_REFUND_READ',
    CONSUME_REFUND_AUDIT: 'CONSUME_REFUND_AUDIT',
    CONSUME_APPEAL_READ: 'CONSUME_APPEAL_READ',
    CONSUME_APPEAL_HANDLE: 'CONSUME_APPEAL_HANDLE',
    CONSUME_DEVICE_READ: 'CONSUME_DEVICE_READ',
    CONSUME_DEVICE_WRITE: 'CONSUME_DEVICE_WRITE',
    CONSUME_REPORT_READ: 'CONSUME_REPORT_READ',
    CONSUME_REPORT_EXPORT: 'CONSUME_REPORT_EXPORT',

    // 菜品管理
    DISH_CATEGORY_READ: 'DISH_CATEGORY_READ',
    DISH_CATEGORY_WRITE: 'DISH_CATEGORY_WRITE',
    DISH_INFO_READ: 'DISH_INFO_READ',
    DISH_INFO_WRITE: 'DISH_INFO_WRITE',
    DISH_PUBLISH: 'DISH_PUBLISH',
    DISH_MENU_READ: 'DISH_MENU_READ',
    DISH_MENU_WRITE: 'DISH_MENU_WRITE',
    DISH_MENU_PUBLISH: 'DISH_MENU_PUBLISH',
    DISH_FEEDBACK_READ: 'DISH_FEEDBACK_READ',
    DISH_FEEDBACK_HANDLE: 'DISH_FEEDBACK_HANDLE',
    DISH_NOTICE_READ: 'DISH_NOTICE_READ',
    DISH_NOTICE_WRITE: 'DISH_NOTICE_WRITE',
    DISH_NOTICE_PUBLISH: 'DISH_NOTICE_PUBLISH',

    // 设备管理
    CONSUME_DEVICE_ADMIN: 'CONSUME_DEVICE_ADMIN',

    // 系统设置
    SYSTEM_ROLE_READ: 'SYSTEM_ROLE_READ',
    SYSTEM_ROLE_WRITE: 'SYSTEM_ROLE_WRITE',
    SYSTEM_ADMIN_READ: 'SYSTEM_ADMIN_READ',
    SYSTEM_ADMIN_WRITE: 'SYSTEM_ADMIN_WRITE',
    SYSTEM_LOG_READ: 'SYSTEM_LOG_READ',
    SYSTEM_CONFIG_READ: 'SYSTEM_CONFIG_READ',
    SYSTEM_CONFIG_WRITE: 'SYSTEM_CONFIG_WRITE',
} as const;

export type PermissionType = (typeof Permission)[keyof typeof Permission];
